ZZRGUSD3 ;Unit Tests - Clinic API; 05/28/2012  11:46 AM
 ;;1.0;UNIT TEST;;05/28/2012;
 TSTART
 S IO=""
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZRGUSD3")
 TROLLBACK
 Q
STARTUP ;
 S DTIME=500,DUZ=1,U="^"
 K XUSER,XOPT
 D LOGON^ZZRGUTCM
 S DT=$P($$HTFM^XLFDT($H),".")
 D SETUP^ZZRGUSDC()
 Q
 ;
SHUTDOWN ;
 Q
 ;
CHKAPP ;
 N RETURN
 S ^DPT(DFN,.35)=DT
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN,.LVL)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: PATDIED")
 D CHKEQ^XTMUNIT(RETURN(0),"PATDIED^PATIENT HAS DIED.^1","Expected error: PATDIED")
 S ^DPT(DFN,.35)="" K RETURN
 S ^SC(SC,"SDPROT")="Y"
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: CLNURGT")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"CLNURGT","Expected error: CLNURGT")
 S ^SC(SC,"SDPRIV",DUZ,0)=DUZ K RETURN
 S TMP=$G(^SC(SC,"ST",DT,1)),^SC(SC,"ST",DT,1)="CANCELLED"
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTCLUV")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTCLUV","Expected error: APTCLUV")
 K RETURN S ^SC(SC,"ST",DT,1)=TMP
 S ^HOLIDAY(DT,0)=DT_U_"Holiday test",$P(^SC(SC,"SL"),U,8)=""
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTSHOL")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTSHOL","Expected error: APTSHOL")
 K RETURN S $P(^SC(SC,"SL"),U,8)="Y"
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,DT+3_".08",LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTEXCD")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTEXCD","Expected error: APTEXCD")
 ;check if patient has an active appointment on the same time
 K RETURN
 S %=$$MAKE^SDMAPI2(.RET,DFN,SC,SD,TYPE,,LEN,NXT,RSN)
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTPAHA")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTPAHA","Expected error: APTPAHA")
 D CHKEQ^XTMUNIT($P(RETURN(0),U,3),2,"Level 2 expected")
 ;check if patient has an active appointment on the same day
 K RETURN
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,DT_".1",LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTPAHA")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTPHSD","Expected error: APTPAHA")
 D CHKEQ^XTMUNIT($P(RETURN(0),U,3),3,"Level 3 expected")
 ;check if patient has an canceled appointment on the same time
 K RETURN
 S $P(^DPT(DFN,"S",SD,0),U,2)="PC"
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTPPCP")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTPPCP","Expected error: APTPPCP")
 D CHKEQ^XTMUNIT($P(RETURN(0),U,3),2,"Level 2 expected")
 ;check if date is prior to patient birth date
 K RETURN,^DPT(DFN,"S")
 S $P(^DPT(DFN,0),U,3)=DT+2
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTPPAB")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTPPAB","Expected error: APTPPAB")
 D CHKEQ^XTMUNIT($P(RETURN(0),U,3),1,"Level 1 expected")
 ;check overbook
 K RETURN
 S %=$$CHKAPP^SDMAPI2(.RETURN,SC,DFN,SD,LEN)
 D CHKEQ^XTMUNIT(RETURN,0,"Expected error: APTPPAB")
 D CHKEQ^XTMUNIT($P(RETURN(0),U),"APTPPAB","Expected error: APTPPAB")
 D CHKEQ^XTMUNIT($P(RETURN(0),U,3),1,"Level 1 expected")
 Q
 ;
XTENT ;
 ;;CHKAPP;Check make apt
