ZZRGUSD5 ;RGI/CBR Unit Tests - Vocabulary API; 01/29/2013
 ;;1.0;UNIT TEST;;05/28/2012;
 Q:$T(^SDMAPI1)=""
 TSTART
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZRGUSD5")
 TROLLBACK
 Q
STARTUP ;
 S DTIME=500,DUZ=1,U="^"
 S DT=$P($$HTFM^XLFDT($H),".")
 Q
 ;
SHUTDOWN ;
 Q
 ;
LSTAPPST ;
 N R,%
 S %=$$LSTAPPST^SDMAPI1(.R)
 D CHKEQ^XTMUNIT(%,1,"Unexpected error: "_$G(RETURN(0)))
 D CHKEQ^XTMUNIT($G(R(0)),8)
 D CHKEQ^XTMUNIT($G(R(1)),"N^NO-SHOW")
 D CHKEQ^XTMUNIT($G(R(2)),"C^CANCELLED BY CLINIC")
 D CHKEQ^XTMUNIT($G(R(3)),"NA^NO-SHOW & AUTO RE-BOOK")
 D CHKEQ^XTMUNIT($G(R(4)),"CA^CANCELLED BY CLINIC & AUTO RE-BOOK")
 D CHKEQ^XTMUNIT($G(R(5)),"I^INPATIENT APPOINTMENT")
 D CHKEQ^XTMUNIT($G(R(6)),"PC^CANCELLED BY PATIENT")
 D CHKEQ^XTMUNIT($G(R(7)),"PCA^CANCELLED BY PATIENT & AUTO-REBOOK")
 D CHKEQ^XTMUNIT($G(R(8)),"NT^NO ACTION TAKEN")
 Q
LSTHLTP ;
 N R,%
 S %=$$LSTHLTP^SDMAPI1(.R)
 D CHKEQ^XTMUNIT(%,1,"Unexpected error: "_$G(RETURN(0)))
 D CHKEQ^XTMUNIT($G(R(0)),8)
 D CHKEQ^XTMUNIT($G(R(1)),"C^CLINIC")
 D CHKEQ^XTMUNIT($G(R(2)),"M^MODULE")
 D CHKEQ^XTMUNIT($G(R(3)),"W^WARD")
 D CHKEQ^XTMUNIT($G(R(4)),"Z^OTHER LOCATION")
 D CHKEQ^XTMUNIT($G(R(5)),"N^NON-CLINIC STOP")
 D CHKEQ^XTMUNIT($G(R(6)),"F^FILE AREA")
 D CHKEQ^XTMUNIT($G(R(7)),"I^IMAGING")
 D CHKEQ^XTMUNIT($G(R(8)),"OR^OPERATING ROOM")
 Q
LSTSRT ;
 N R,%
 S %=$$LSTSRT^SDMAPI1(.R)
 D CHKEQ^XTMUNIT(%,1,"Unexpected error: "_$G(RETURN(0)))
 D CHKEQ^XTMUNIT($G(R(0)),7)
 D CHKEQ^XTMUNIT($G(R(1)),"N^'NEXT AVAILABLE' APPT.")
 D CHKEQ^XTMUNIT($G(R(2)),"C^OTHER THAN 'NEXT AVA.' (CLINICIAN REQ.)")
 D CHKEQ^XTMUNIT($G(R(3)),"P^OTHER THAN 'NEXT AVA.' (PATIENT REQ.)")
 D CHKEQ^XTMUNIT($G(R(4)),"W^WALKIN APPT.")
 D CHKEQ^XTMUNIT($G(R(5)),"M^MULTIPLE APPT. BOOKING")
 D CHKEQ^XTMUNIT($G(R(6)),"A^AUTO REBOOK")
 D CHKEQ^XTMUNIT($G(R(7)),"O^OTHER THAN 'NEXT AVA.' APPT.")
 Q
LSTSBCTG
 Q:$T(^DGSAAPI)=""
 D SUBTYP^ZZRGUSDC
 N R,%
 S %=$$LSTSBCTG^DGSAAPI(.R)
 D CHKEQ^XTMUNIT(%,1,"Unexpected error: "_$G(RETURN(0)))
 D CHKEQ^XTMUNIT($G(R(0)),2)
 D CHKEQ^XTMUNIT($G(R(1)),"1^Sharing 1")
 D CHKEQ^XTMUNIT($G(R(2)),"2^Sharing 2")
 Q
XTENT ;
 ;;LSTAPPST;List appointment statuses
 ;;LSTHLTP;List hospital location types
 ;;LSTSRT;List scheduling request types
 ;;LSTSBCTG;List sharing agreement sub-categories
