ZZDGPMAPI8 ;Unit Tests - Clinic API; 4/23/13
 ;;1.0;UNIT TEST;;05/28/2012;
 TSTART
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZDGPMAPI8")
 TROLLBACK
 Q
STARTUP ;
 S DTIME=500,DUZ=1,U="^"
 K XUSER,XOPT
 D LOGON^ZZRGUTCM
 S DT=$P($$HTFM^XLFDT($H),".")
 D SETUP^ZZDGPMSE()
 Q
 ;
SHUTDOWN ;
 Q
 ;
CHKIN ;
 S PA("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1),PA("LDGCOMM")="Check-in diagnosis",PA("LDGRSN")=1
 S PA("PATIENT")=DFN,PA("TYPE")="43^",PA("WARD")=WARD1
 S %=$$LDGIN^DGPMAPI4(.R,.PA)
 Q
LSTADTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTADTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID")_U_RE(1,"NAME"),"4^A/C","A/C admission")
 D CHKEQ^XTMUNIT(RE(2,"ID")_U_RE(2,"NAME"),"1^DIRECT","Direct admission")
 D CHKEQ^XTMUNIT(RE(3,"ID")_U_RE(3,"NAME"),"6^NON-VETERAN","Non-veteran admission")
 D CHKEQ^XTMUNIT(RE(4,"ID")_U_RE(4,"NAME"),"2^OPT-NSC","Opt-nsc admission")
 D CHKEQ^XTMUNIT(RE(5,"ID")_U_RE(5,"NAME"),"3^OPT-SC","Opt-sc admission")
 D CHKEQ^XTMUNIT(RE(6,"ID")_U_RE(6,"NAME"),"8^PBC","PBC admission")
 D CHKEQ^XTMUNIT(RE(7,"ID")_U_RE(7,"NAME"),"5^TRANSFER IN","Transfer in admission")
 D CHKEQ^XTMUNIT(RE(8,"ID")_U_RE(8,"NAME"),"7^WAITING LIST","Waiting list admission")
 D CHKMFN("MFN")
 Q
CHKMFN(PNAME,ERR) ;
 S:'$D(ERR) ERR="MVTNFND"
 S TMP=$G(@PNAME)
 S @PNAME="AAA" X RTN
 D CHKEQ^XTMUNIT(RE_U_$P($G(RE(0)),U),"0^INVPARM","Wrong mvt id")
 D CHKEQ^XTMUNIT(RE(0)[PNAME,1,"Invalid MFN parameter")
 S @PNAME="10001^AAA" X RTN
 D CHKEQ^XTMUNIT(RE_U_$P($G(RE(0)),U),"0^"_ERR,"Movement not found")
 S @PNAME=TMP
 Q
LSTCOTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTCOTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 ;D CHKIN
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID"),45,"Check-out ID")
 D CHKEQ^XTMUNIT(RE(1,"NAME"),"CHECK-OUT LODGER","Check-out name")
 D CHKMFN("MFN")
 Q
LSTCITYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTCITYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID"),43,"Check-in ID 1")
 D CHKEQ^XTMUNIT(RE(2,"ID"),44,"Check-in ID 2")
 D CHKEQ^XTMUNIT(RE(1,"NAME"),"CHECK-IN LODGER","Check-in name 1")
 D CHKEQ^XTMUNIT(RE(2,"NAME"),"CHECK-IN LODGER (OTHER FACILITY)","Check-in name 2")
 D CHKMFN("MFN")
 Q
LSTTRTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTTRTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 S %=$$LSTTRTYP^DGPMAPI7(.RE,,,,"AAA",.DGDT,.MFN)
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(+RE(0),0,"Empty list")
 S AFN=$$ADM^ZZDGPMAPI6(,$$FMADD^XLFDT($$NOW^XLFDT(),,-1))
 S DGDT=$$NOW^XLFDT(),DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID")_U_RE(1,"NAME"),"11^INTERWARD TRANSFER","Interward transfer")
 D CHKEQ^XTMUNIT(RE(2,"ID")_U_RE(2,"NAME"),"20^TO ASIH (OTHER FACILITY)","To ASIH other")
 D CHKEQ^XTMUNIT(RE(3,"ID")_U_RE(3,"NAME"),"13^TO ASIH FROM NHCU/DOM","To ASIH")
 D CHKEQ^XTMUNIT(RE(4,"ID")_U_RE(4,"NAME"),"16^TO AUTHORIZED ABSENCE","To auth absence")
 D CHKEQ^XTMUNIT(RE(5,"ID")_U_RE(5,"NAME"),"18^TO AUTHORIZED ABSENCE <96 HRS","To auth absence <96")
 D CHKEQ^XTMUNIT(RE(6,"ID")_U_RE(6,"NAME"),"17^TO UNAUTHORIZED ABSENCE","To unauth absence")
 D CHKMFN("MFN")
 Q
LSTDTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTDTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT=$$NOW^XLFDT(),DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID")_U_RE(1,"NAME"),"27^DEATH","Death")
 D CHKEQ^XTMUNIT(RE(2,"ID")_U_RE(2,"NAME"),"32^DEATH WITH AUTOPSY","Death with autopsy")
 D CHKEQ^XTMUNIT(RE(3,"ID")_U_RE(3,"NAME"),"30^IRREGULAR","Irregular")
 D CHKEQ^XTMUNIT(RE(4,"ID")_U_RE(4,"NAME"),"47^IRREGULAR FM UA","Irregular FM UA")
 D CHKEQ^XTMUNIT(RE(5,"ID")_U_RE(5,"NAME"),"31^NBC","NBC")
 D CHKEQ^XTMUNIT(RE(6,"ID")_U_RE(6,"NAME"),"29^NON-VETERAN","Non veteran")
 D CHKEQ^XTMUNIT(RE(7,"ID")_U_RE(7,"NAME"),"25^OPT-NSC","OPT-NSC")
 D CHKEQ^XTMUNIT(RE(8,"ID")_U_RE(8,"NAME"),"26^OPT-SC","OPT-SC")
 D CHKEQ^XTMUNIT(RE(9,"ID")_U_RE(9,"NAME"),"24^REGULAR","Regular")
 D CHKEQ^XTMUNIT(RE(10,"ID")_U_RE(10,"NAME"),"28^TRANSFER OUT","Transfer out")
 D CHKMFN("MFN")
 S DGDT=$$FMADD^XLFDT($$NOW^XLFDT(),,-4) X RTN
 D CHKEQ^XTMUNIT(+RE(0),0,"Empty list")
 S %=$$DELADM^DGPMAPI1(.RE,AFN)
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(+RE(0),0,"Empty list")
 Q
GETADM ;
 N RE,ADM
 S ADT=$$FMADD^XLFDT($$NOW^XLFDT(),,-6),EADT=$$UP^XLFSTR($$FMTE^XLFDT(ADT))
 S AFN=$$ADM^ZZDGPMAPI6(.ADM,ADT)
 S RTN="S %=$$GETADM^DGPMAPI8(.RE,AFN)"
 D CHKMFN("AFN","ADMNFND")
 X RTN
 S N0=^DGPM(+AFN,0)
 D CHKEQ^XTMUNIT(RE("ADMCAT"),"0^")
 D CHKEQ^XTMUNIT(RE("ADMREG"),"1^ACTIVE PSYCHOSIS")
 D CHKEQ^XTMUNIT(RE("ADMSCC"),"1^YES")
 D CHKEQ^XTMUNIT(RE("ADMSRC"),"1^1D")
 D CHKEQ^XTMUNIT(RE("ASIHTRA"),"")
 D CHKEQ^XTMUNIT(RE("ATNDPHY"),+DUZ_U_$P(^VA(200,+DUZ,0),U),"Attending physician")
 D CHKEQ^XTMUNIT(RE("DATE"),ADT_U_EADT,"Movement date")
 D CHKEQ^XTMUNIT(RE("DIAG",1),"Admit diagnosis","Diagnosis")
 D CHKEQ^XTMUNIT(RE("DISCH"),"","Discharge IEN")
 D CHKEQ^XTMUNIT(RE("ELIGIB"),"0^","Eligibility code")
 D CHKEQ^XTMUNIT(RE("FDEXC"),"1^YES","Facility directory exclusion")
 D CHKEQ^XTMUNIT(RE("FTSPEC"),"1^MEDICAL OBSERVATION","Facility treating specialty")
 D CHKEQ^XTMUNIT(RE("MASTYPE"),"15^DIRECT","MAS movement type")
 D CHKEQ^XTMUNIT(RE("PATIENT"),DFN,"Patient")
 D CHKEQ^XTMUNIT(RE("PRYMPHY"),"","Primary physician")
 D CHKEQ^XTMUNIT(RE("ROOMBED"),+BED1_"^R101-BED-1","Bed")
 D CHKEQ^XTMUNIT(RE("SERILL"),"^","Seriously ill")
 D CHKEQ^XTMUNIT(RE("SHDIAG"),"Admit diagnosis","Short diagnosis")
 D CHKEQ^XTMUNIT(RE("TTYPE"),"1^ADMISSION","Transaction type")
 D CHKEQ^XTMUNIT(RE("TYPE"),"1^DIRECT","Admission type")
 D CHKEQ^XTMUNIT(RE("WARD"),+WARD1_"^Ward NHC 1","Ward")
 ; After discharge
 N DDT,EDDT
 S DDT=$$FMADD^XLFDT($$NOW^XLFDT(),,-2),EDDT=$$UP^XLFSTR($$FMTE^XLFDT(DDT))
 S DMFN=$$DISCH^ZZDGPMAPI6(AFN,DDT)
 X RTN
 D CHKEQ^XTMUNIT(RE("DISCH"),DMFN_U_EDDT,"Discharge IEN")
 Q
GETTRA ;
 N RE,ADM
 S TDT=$$FMADD^XLFDT($$NOW^XLFDT(),,-3),ETDT=$$UP^XLFSTR($$FMTE^XLFDT(TDT))
 S TFN=$$TRA^ZZDGPMAPI6(AFN,TDT)
 S RTN="S %=$$GETTRA^DGPMAPI8(.RE,TFN)"
 D CHKMFN("TFN","TRANFND")
 X RTN
 S N0=^DGPM(+AFN,0)
 D CHKEQ^XTMUNIT(RE("ATNDPHY"),+DUZ_U_$P(^VA(200,+DUZ,0),U),"Attending physician")
 D CHKEQ^XTMUNIT(RE("DATE"),TDT_U_ETDT,"Movement date")
 D CHKEQ^XTMUNIT(RE("FTSPEC"),"2^SURGICAL OBSERVATION","Facility treating specialty")
 D CHKEQ^XTMUNIT(RE("MASTYPE"),"4^INTERWARD TRANSFER","MAS movement type")
 D CHKEQ^XTMUNIT(RE("PATIENT"),DFN,"Patient")
 D CHKEQ^XTMUNIT(RE("PRYMPHY"),+DUZ_U_$P(^VA(200,+DUZ,0),U),"Primary physician")
 D CHKEQ^XTMUNIT(RE("ROOMBED"),+BED2_"^R102-BED-2","Bed")
 D CHKEQ^XTMUNIT(RE("TTYPE"),"2^TRANSFER","Transaction type")
 D CHKEQ^XTMUNIT(RE("TYPE"),"11^INTERWARD TRANSFER","Transfer type")
 D CHKEQ^XTMUNIT(RE("WARD"),+WARD1_"^Ward NHC 1","Ward")
 D CHKEQ^XTMUNIT(RE("ADMIFN"),AFN_U_EADT,"Admission IEN")
 D CHKEQ^XTMUNIT(RE("FCTY"),"","Transfer facility")
 D CHKEQ^XTMUNIT(RE("RABSDT"),"","Absence return date")
 Q
GETMVT ;
 N RE,MFN
 S MDT=$$FMADD^XLFDT($$NOW^XLFDT(),,-1),EMDT=$$UP^XLFSTR($$FMTE^XLFDT(MDT))
 S (CIFN,MFN)=+$$CHECKIN^ZZDGPMAPI5(MDT)
 S RTN="S %=$$GETMVT^DGPMAPI8(.RE,MFN)"
 D CHKMFN("MFN","MVTNFND")
 X RTN
 D CHKEQ^XTMUNIT(RE("DATE"),MDT_U_EMDT,"Movement date")
 D CHKEQ^XTMUNIT(RE("MASTYPE"),"5^CHECK-IN LODGER","MAS movement type")
 D CHKEQ^XTMUNIT(RE("PATIENT"),DFN,"Patient")
 D CHKEQ^XTMUNIT(RE("ROOMBED"),+BED2_"^R102-BED-2","Bed")
 D CHKEQ^XTMUNIT(RE("TTYPE"),"4^CHECK-IN LODGER","Transaction type")
 D CHKEQ^XTMUNIT(RE("TYPE"),"43^CHECK-IN LODGER","Transfer type")
 D CHKEQ^XTMUNIT(RE("WARD"),+WARD1_"^Ward NHC 1","Ward")
 D CHKEQ^XTMUNIT(RE("ADMIFN"),MFN_U_EMDT,"Admission IEN")
 D CHKEQ^XTMUNIT(RE("FCTY"),"","Transfer facility")
 D CHKEQ^XTMUNIT(RE("DISCH"),"","Discharge IEN")
 D CHKEQ^XTMUNIT(RE("LDGCOMM"),"Check-in comments","Check-in comments")
 D CHKEQ^XTMUNIT(RE("LDGDISP"),"","Lodger disposition")
 D CHKEQ^XTMUNIT(RE("LDGRSN"),"1^INCLEMENT WEATHER","Lodger reason")
 ; After check-out
 S CODT=$$FMADD^XLFDT($$NOW^XLFDT(),,-0.1),ECODT=$$UP^XLFSTR($$FMTE^XLFDT(CODT))
 S OFN=MFN
 S MFN=+$$CHECKOUT^ZZDGPMAPI5(MFN,CODT)
 X RTN S COFN=MFN
 D CHKEQ^XTMUNIT(RE("DATE"),CODT_U_ECODT,"Movement date")
 D CHKEQ^XTMUNIT(RE("MASTYPE"),"7^CHECK-OUT LODGER","MAS movement type")
 D CHKEQ^XTMUNIT(RE("PATIENT"),DFN,"Patient")
 D CHKEQ^XTMUNIT(RE("ROOMBED"),"","Bed")
 D CHKEQ^XTMUNIT(RE("TTYPE"),"5^CHECK-OUT LODGER","Transaction type")
 D CHKEQ^XTMUNIT(RE("TYPE"),"45^CHECK-OUT LODGER","Transfer type")
 D CHKEQ^XTMUNIT(RE("WARD"),"","Ward")
 D CHKEQ^XTMUNIT(RE("ADMIFN"),OFN_U_EMDT,"Admission IEN")
 D CHKEQ^XTMUNIT(RE("FCTY"),"","Transfer facility")
 D CHKEQ^XTMUNIT(RE("DISCH"),"","Discharge IEN")
 D CHKEQ^XTMUNIT(RE("LDGCOMM"),"","Check-in comments")
 D CHKEQ^XTMUNIT(RE("LDGDISP"),"a^ADMITTED","Lodger disposition")
 D CHKEQ^XTMUNIT(RE("LDGRSN"),"","Lodger reason")
 S MFN=OFN X RTN
 D CHKEQ^XTMUNIT(RE("DISCH"),COFN_U_ECODT,"Discharge IEN")
 Q
GETLASTM ;
 N RE S TDFN=DFN
 S RTN="S %=$$GETLASTM^DGPMAPI8(.RE,.DF,.DGDT)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 K DGDT X RTN
 D CHKEQ^XTMUNIT(+RE("ADMDT"),+MDT,"Admission date")
 D CHKEQ^XTMUNIT(+RE("DATE"),+CODT,"Movement date")
 D CHKEQ^XTMUNIT(RE("MASTYPE"),"7","MAS movement type")
 D CHKEQ^XTMUNIT(RE("ROOMBED"),+BED2_"^R102-BED-2","Bed")
 D CHKEQ^XTMUNIT(RE("TYPE"),"5","Transaction type")
 D CHKEQ^XTMUNIT(RE("WARD"),+WARD1_"^Ward NHC 1","Ward")
 D CHKEQ^XTMUNIT(RE("ADMIFN"),CIFN,"Admission IEN")
 D CHKEQ^XTMUNIT(RE("DISIFN"),COFN,"Discharge IEN")
 D CHKEQ^XTMUNIT(RE("DISTYPE"),"CHECK-OUT LODGER","Discharge type")
 D CHKEQ^XTMUNIT(+RE("DISDT"),+CODT,"Discharge date")
 D CHKEQ^XTMUNIT(RE("MFN"),COFN,"Last movement IEN")
 D CHKEQ^XTMUNIT(RE("MTYPE"),"45^CHECK-OUT LODGER","Last movement type")
 Q
XTENT ;
 ;;LSTADTYP;Admission types
 ;;LSTTRTYP;Transfer types
 ;;LSTDTYP;Transfer types
 ;;LSTCITYP;Check-in types
 ;;LSTCOTYP;Check-out types
 ;;GETADM;Get admission
 ;;GETTRA;Get transfer
 ;;GETMVT;Get movement
 ;;GETLASTM;Get last movement
