ZZDGPMAPI8 ;Unit Tests - Clinic API; 4/2/13
 ;;1.0;UNIT TEST;;05/28/2012;
 TSTART
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZDGPMAPI8")
 TROLLBACK
 Q
STARTUP ;
 S DTIME=500,DUZ=1,U="^"
 K XUSER,XOPT
 D LOGON^ZZRGUTCM
 S DT=$P($$HTFM^XLFDT($H),".")
 D SETUP^ZZDGPMSE()
 Q
 ;
SHUTDOWN ;
 Q
 ;
CHKIN ;
 S PA("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1),PA("LDGCOMM")="Check-in diagnosis",PA("LDGRSN")=1
 S PA("PATIENT")=DFN,PA("TYPE")="43^",PA("WARD")=WARD1
 S %=$$LDGIN^DGPMAPI4(.R,.PA)
 Q
LSTADTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTADTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID")_U_RE(1,"NAME"),"4^A/C","A/C admission")
 D CHKEQ^XTMUNIT(RE(2,"ID")_U_RE(2,"NAME"),"1^DIRECT","Direct admission")
 D CHKEQ^XTMUNIT(RE(3,"ID")_U_RE(3,"NAME"),"6^NON-VETERAN","Non-veteran admission")
 D CHKEQ^XTMUNIT(RE(4,"ID")_U_RE(4,"NAME"),"2^OPT-NSC","Opt-nsc admission")
 D CHKEQ^XTMUNIT(RE(5,"ID")_U_RE(5,"NAME"),"3^OPT-SC","Opt-sc admission")
 D CHKEQ^XTMUNIT(RE(6,"ID")_U_RE(6,"NAME"),"8^PBC","PBC admission")
 D CHKEQ^XTMUNIT(RE(7,"ID")_U_RE(7,"NAME"),"5^TRANSFER IN","Transfer in admission")
 D CHKEQ^XTMUNIT(RE(8,"ID")_U_RE(8,"NAME"),"7^WAITING LIST","Waiting list admission")
 D CHKMFN
 Q
CHKMFN ;
 S MFN="AAA" X RTN
 D CHKEQ^XTMUNIT(RE_U_$P($G(RE(0)),U),"0^INVPARM","Wrong mvt id")
 D CHKEQ^XTMUNIT(RE(0)["MFN",1,"Invalid MFN parameter")
 S MFN="10001^AAA" X RTN
 D CHKEQ^XTMUNIT(RE_U_$P($G(RE(0)),U),"0^MVTNFND","Movement not found")
 Q
LSTCOTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTCOTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 ;D CHKIN
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID"),45,"Check-out ID")
 D CHKEQ^XTMUNIT(RE(1,"NAME"),"CHECK-OUT LODGER","Check-out name")
 D CHKMFN
 Q
LSTCITYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTCITYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID"),43,"Check-in ID 1")
 D CHKEQ^XTMUNIT(RE(2,"ID"),44,"Check-in ID 2")
 D CHKEQ^XTMUNIT(RE(1,"NAME"),"CHECK-IN LODGER","Check-in name 1")
 D CHKEQ^XTMUNIT(RE(2,"NAME"),"CHECK-IN LODGER (OTHER FACILITY)","Check-in name 2")
 D CHKMFN
 Q
LSTTRTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTTRTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(+RE(0),0,"Empty list")
 D ADMIT
 S DGDT=$$NOW^XLFDT(),DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID")_U_RE(1,"NAME"),"11^INTERWARD TRANSFER","Interward transfer")
 D CHKEQ^XTMUNIT(RE(2,"ID")_U_RE(2,"NAME"),"20^TO ASIH (OTHER FACILITY)","To ASIH other")
 D CHKEQ^XTMUNIT(RE(3,"ID")_U_RE(3,"NAME"),"13^TO ASIH FROM NHCU/DOM","To ASIH")
 D CHKEQ^XTMUNIT(RE(4,"ID")_U_RE(4,"NAME"),"16^TO AUTHORIZED ABSENCE","To auth absence")
 D CHKEQ^XTMUNIT(RE(5,"ID")_U_RE(5,"NAME"),"18^TO AUTHORIZED ABSENCE <96 HRS","To auth absence <96")
 D CHKEQ^XTMUNIT(RE(6,"ID")_U_RE(6,"NAME"),"17^TO UNAUTHORIZED ABSENCE","To unauth absence")
 D CHKMFN
 Q
LSTDTYP ;
 N RE,DF,DGDT,RTN,MFN
 S RTN="S %=$$LSTDTYP^DGPMAPI7(.RE,,,,.DF,.DGDT,.MFN)"
 D CHKPAT^ZZDGPMSE(RTN,,"DF")
 D VALDT^ZZDGPMUTL(RTN,"DGDT")
 S DGDT=$$NOW^XLFDT(),DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(RE(1,"ID")_U_RE(1,"NAME"),"27^DEATH","Death")
 D CHKEQ^XTMUNIT(RE(2,"ID")_U_RE(2,"NAME"),"32^DEATH WITH AUTOPSY","Death with autopsy")
 D CHKEQ^XTMUNIT(RE(3,"ID")_U_RE(3,"NAME"),"30^IRREGULAR","Irregular")
 D CHKEQ^XTMUNIT(RE(4,"ID")_U_RE(4,"NAME"),"47^IRREGULAR FM UA","Irregular FM UA")
 D CHKEQ^XTMUNIT(RE(5,"ID")_U_RE(5,"NAME"),"31^NBC","NBC")
 D CHKEQ^XTMUNIT(RE(6,"ID")_U_RE(6,"NAME"),"29^NON-VETERAN","Non veteran")
 D CHKEQ^XTMUNIT(RE(7,"ID")_U_RE(7,"NAME"),"25^OPT-NSC","OPT-NSC")
 D CHKEQ^XTMUNIT(RE(8,"ID")_U_RE(8,"NAME"),"26^OPT-SC","OPT-SC")
 D CHKEQ^XTMUNIT(RE(9,"ID")_U_RE(9,"NAME"),"24^REGULAR","Regular")
 D CHKEQ^XTMUNIT(RE(10,"ID")_U_RE(10,"NAME"),"28^TRANSFER OUT","Transfer out")
 D CHKMFN
 S %=$$DELADM^DGPMAPI1(.RE,AFN)
 S DGDT="",DF=DFN
 X RTN
 D CHKEQ^XTMUNIT(+RE(0),0,"Empty list")
 Q
ADMIT ;
 S ADM("PATIENT")=+DFN,ADM("TYPE")=1,ADM("ADMREG")=1,ADM("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1)_U
 S ADM("FDEXC")=1,ADM("SHDIAG")="Transfer Admit diagnosis",ADM("WARD")=WARD1,ADM("FTSPEC")="1^"
 S ADM("ATNDPHY")=DUZ_U ;,ADM("ROOMBED")=BED1_U
 S %=$$ADMIT^DGPMAPI1(.RT,.ADM),AFN=+RT
 Q
XTENT ;
 ;;LSTADTYP;Admission types
 ;;LSTTRTYP;Transfer types
 ;;LSTDTYP;Transfer types
 ;;LSTCITYP;Check-in types
 ;;LSTCOTYP;Check-out types
