ZZDGPMAPI3 ;Unit Tests - Clinic API; 2/20/2013
 ;;1.0;UNIT TEST;;05/28/2012;
 TSTART
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZDGPMAPI3")
 TROLLBACK
 Q
STARTUP ;
 S DTIME=500,DUZ=1,U="^"
 K XUSER,XOPT
 D LOGON^ZZRGUTCM
 S DT=$P($$HTFM^XLFDT($H),".")
 D SETUP^ZZDGPMSE()
 Q
 ;
SHUTDOWN ;
 Q
DSCH ;
 N DATE
 S ADM("PATIENT")=DFN,ADM("TYPE")=1,ADM("ADMREG")=1,ADM("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-3)_U
 S ADM("FDEXC")=1,ADM("SHDIAG")="Transfer Admit diagnosis",ADM("WARD")=WARD1,ADM("FTSPEC")="1^",ADM("ATNDPHY")=DUZ
 S DATE=ADM("DATE") M ADM1=ADM
 S %=$$ADMIT^DGPMAPI1(.RT,.ADM) S AFN=+RT
 ;invalid admission
 S %=$$DISCH^DGPMAPI3(.RE,.DIS)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: INVPARM")
 D CHKEQ^XTMUNIT($P(RE(0),U,2)["'ADMIFN'",1,"Expected error: INVPARM")
 S DIS("ADMIFN")=AFN+3_U,%=$$DISCH^DGPMAPI3(.RE,.DIS)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: ADMNFND")
 D CHKEQ^XTMUNIT($P(RE(0),U),"ADMNFND","Expected error: ADMNFND")
 ;invalid date param
 S DIS("ADMIFN")=AFN_U,%=$$DISCH^DGPMAPI3(.RE,.DIS)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: INVPARM")
 D CHKEQ^XTMUNIT($P(RE(0),U,2)["'DATE'",1,"Expected error: INVPARM")
 ;not before admission
 S DIS("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-3,-1)_U,%=$$DISCH^DGPMAPI3(.RE,.DIS)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: TRANBADM")
 D CHKEQ^XTMUNIT($P(RE(0),U),"TRANBADM","Expected error: TRANBADM")
 ;not before last movement
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1)_U,PAR("ADMIFN")=AFN_U,PAR("TYPE")="18^"
 S %=$$TRANSF^DGPMAPI2(.RE,.PAR)
 S DIS("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-2)_U,%=$$DISCH^DGPMAPI3(.RE,.DIS)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DCHNBLM")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DCHNBLM","Expected error: DCHNBLM")
 ;invali type
 S DIS("DATE")=$$NOW^XLFDT()_U,DIS("TYPE")="1^",RTN="S %=$$DISCH^DGPMAPI3(.RE,.DIS)"
 D CHKTYPE^ZZDGPMAPI1(RTN,.DIS)
 S PAR("TYPE")="1^" X RTN
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DISINVAT")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DISINVAT","Expected error: DISINVAT")
 D CHKEQ^XTMUNIT($P(RE(0),U,2)["DIRECT",1,"Expected error: DISINVAT")
 S PAR("TYPE")="24^"
 ;ok
 S DIS("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),,-3)_U,DIS("TYPE")=24,DIS("ADMIFN")=AFN
 M DIS1=DIS
 S %=$$DISCH^DGPMAPI3(.RE,.DIS),DISCH=+RE
 D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 ;already discharged
 S %=$$DISCH^DGPMAPI3(.RE,.DIS1)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DCHPADON")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DCHPADON","Expected error: DCHPADON")
 ;cleaning up
 S ADM1("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),,-2)_U
 S %=$$ADMIT^DGPMAPI1(.RE,.ADM1) S AFN1=+RE
 ;only last discharge
 S %=$$DELDSCH^DGPMAPI3(.RE,DISCH_U)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DCHCDOLA")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DCHCDOLA","Expected error: DCHCDOLA")
 ;
 S %=$$DELADM^DGPMAPI1(.RE,AFN1_U)
 S %=$$DELADM^DGPMAPI1(.RE,AFN_U)
 D CHKEQ^XTMUNIT(RE>0,1,"Unexpected error: "_$G(RE(0)))
 Q
FROMASIH ;
 S ADM("PATIENT")=DFN,ADM("TYPE")=1,ADM("ADMREG")=1,ADM("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-3)_U
 S ADM("FDEXC")=1,ADM("SHDIAG")="Transfer Admit diagnosis",ADM("WARD")=WARD1,ADM("FTSPEC")="1^",ADM("ATNDPHY")=DUZ_U
 S %=$$ADMIT^DGPMAPI1(.RT,.ADM),AFN=RT_U
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1)_U,PAR("ADMIFN")=RT_U
 S PAR("ADMREG")="75^",PAR("ADMSRC")="53^",PAR("FDEXC")="0^",PAR("FTSPEC")="41^",PAR("PATIENT")=DFN,PAR("ATNDPHY")=DUZ_U
 S PAR("PRYMPHY")=DUZ_U,PAR("ROOMBED")=BED2_U,PAR("SHDIAG")="To asih diagnosis",PAR("TYPE")="13^",PAR("WARD")=WARD2_U
 S $P(^DIC(42,+WARD2,0),U,3)="M"
 S %=$$TRANSF^DGPMAPI2(.RE,.PAR)
 D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 ;discharge
 S %=$$GETLASTM^DGPMAPI8(.LMVT,DFN)
 S PAR("DATE")=+PAR("DATE")+0.02,PAR("TYPE")=33,PAR("ADMIFN")=LMVT("ADMIFN")
 S %=$$DISCH^DGPMAPI3(.RE,.PAR),DISCH=+RE
 D CHKEQ^XTMUNIT(RE>0,1,"Unexpected error: "_$G(RE(0)))
 ;cleaning up
 S %=$$GETLASTM^DGPMAPI8(.LMVT,DFN)
 S %=$$DELTRA^DGPMAPI2(.RE,LMVT("MFN"))
 S %=$$DELDSCH^DGPMAPI3(.RE,DISCH)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DCHCDWAH")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DCHCDWAH","Expected error: DCHCDWAH")
 ; 
 S %=$$GETLASTM^DGPMAPI8(.LMVT,DFN)
 S %=$$DELADM^DGPMAPI1(.RE,LMVT("ADMIFN"))
 D CHKEQ^XTMUNIT(RE>0,1,"Unexpected error: "_$G(RE(0)))
 S %=$$DELADM^DGPMAPI1(.RE,AFN)
 D CHKEQ^XTMUNIT(RE>0,1,"Unexpected error: "_$G(RE(0)))
 Q
 ;
TRAOUT ;
 S ADM("PATIENT")=DFN,ADM("TYPE")=1,ADM("ADMREG")=1,ADM("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-3)_U
 S ADM("FDEXC")=1,ADM("SHDIAG")="Transfer Admit diagnosis",ADM("WARD")=WARD1,ADM("FTSPEC")="1^",ADM("ATNDPHY")=DUZ
 S %=$$ADMIT^DGPMAPI1(.RT,.ADM),AFN=RT_U
 ;discharge
 S PAR("DATE")=(+PAR("DATE")+0.02)_U,PAR("TYPE")="28"_U,PAR("ADMIFN")=AFN
 S %=$$DISCH^DGPMAPI3(.RE,.PAR),DISCH=+RE
 D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 S %=$$DELDSCH^DGPMAPI3(.RE,DISCH)
 D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 S %=$$DELADM^DGPMAPI1(.RE,AFN)
 D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 Q
 ;
UPDDSCH ;Update discharge
 S ADM("PATIENT")=DFN,ADM("TYPE")=1,ADM("ADMREG")=1,ADM("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-3)_U
 S ADM("FDEXC")=1,ADM("SHDIAG")="Transfer Admit diagnosis",ADM("WARD")=WARD1,ADM("FTSPEC")="1^",ADM("ATNDPHY")=DUZ
 S %=$$ADMIT^DGPMAPI1(.RT,.ADM),AFN=RT_U
 ;discharge
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-2)_U,PAR("TYPE")="24"_U,PAR("ADMIFN")=AFN
 S %=$$DISCH^DGPMAPI3(.RE,.PAR),DISCH=+RE_U
 ;not before last movement
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-4)_U,PAR("TYPE")="25"_U,PAR("ADMIFN")=AFN
 S %=$$UPDDSCH^DGPMAPI3(.RE,.PAR,DISCH)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DCHNBLM")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DCHNBLM","Expected error: DCHNBLM")
 ;invalid type
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1)_U,PAR("TYPE")="23"_U,PAR("ADMIFN")=AFN
 S %=$$UPDDSCH^DGPMAPI3(.RE,.PAR,DISCH)
 D CHKEQ^XTMUNIT(RE,0,"Expected error: DISINVAT")
 D CHKEQ^XTMUNIT($P(RE(0),U),"DISINVAT","Expected error: DISINVAT")
 ;ok to update
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1)_U,PAR("TYPE")="25"_U,PAR("ADMIFN")=AFN
 S %=$$UPDDSCH^DGPMAPI3(.RE,.PAR,DISCH)
 D CHKEQ^XTMUNIT(RE,1,"Unexpected error: "_$G(RE(0)))
 Q
XTENT ;
 ;;DSCH;Discharge
 ;;FROMASIH;Discharge from asih.
 ;;TRAOUT;Transfer out
 ;;UPDDSCH;Update discharge
