ZZDGPMAPI3 ;Unit Tests - Clinic API; 2/11/2013
 ;;1.0;UNIT TEST;;05/28/2012;
 TSTART
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZDGPMAPI3")
 TROLLBACK
 Q
STARTUP ;
 S DTIME=500,DUZ=1,U="^"
 K XUSER,XOPT
 D LOGON^ZZRGUTCM
 S DT=$P($$HTFM^XLFDT($H),".")
 D SETUP^ZZDGPMSE()
 Q
 ;
SHUTDOWN ;
 Q
FROMASIH ;
 S ADM("PATIENT")=DFN,ADM("TYPE")=1,ADM("ADMREG")=1,ADM("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-3)_U
 S ADM("FDEXC")=1,ADM("SHDIAG")="Transfer Admit diagnosis",ADM("WARD")=WARD1,ADM("FTSPEC")="1^",ADM("ATNDPHY")=DUZ
 S %=$$ADMIT^DGPMAPI1(.RT,.ADM)
 S PAR("DATE")=$$FMADD^XLFDT($$NOW^XLFDT(),-1)_U,PAR("ADMIFN")=RT_U
 S PAR("ADMREG")="75^",PAR("ADMSRC")="53^",PAR("FDEXC")="0^",PAR("FTSPEC")="41^",PAR("PATIENT")=DFN,PAR("ATNDPHY")=DUZ
 S PAR("PRYMPHY")=DUZ_U,PAR("ROOMBED")=BED2_U,PAR("SHDIAG")="To asih diagnosis",PAR("TYPE")=13,PAR("WARD")=WARD2_U
 S $P(^DIC(42,+WARD2,0),U,3)="M"
 S %=$$TRANSF^DGPMAPI2(.RE,.PAR)
 D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 ;discharge
 S %=$$GETLASTM^DGPMAPI8(.LMVT,DFN)
 S PAR("DATE")=+PAR("DATE")+0.02,PAR("TYPE")=33,PAR("ADMIFN")=LMVT("ADMIFN")
 ;S %=$$DISCH^DGPMAPI3(.RE,.PAR),DISCH=+RE
 ;D CHKEQ^XTMUNIT(RE>0,1,"Expected error: ASHWINVS")
 Q
 ;
XTENT ;
 ;;FROMASIH;Discharge from asih.
